name: technovation2020
description: Notification app for Technovation 2020 - The Techno-Cultural fest organised by CSEA department of IGIT Sarang.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.23.1
  carousel_slider: ^1.3.1
  firebase_database: ^3.1.1
  firebase_messaging: ^6.0.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/event1.jpg
   - images/event2.jpg
   - images/event3.jpg
   - images/event4.jpg
   - images/event5.jpg
   - images/000.jpg
   - images/001.jpg
   - images/002.jpg
   - images/003.jpg
   - images/004.jpg
   - images/005.jpg
   - images/006.jpg
   - images/007.jpg
   - images/008.jpg
   - images/100.jpg
   - images/101.jpg
   - images/102.jpg
   - images/103.jpg
   - images/104.jpg
   - images/105.jpg
   - images/106.jpg
   - images/107.jpg
   - images/108.jpg
   - images/200.jpg
   - images/201.jpg
   - images/202.jpg
   - images/203.jpg
   - images/204.jpg
   - images/205.jpg
   - images/206.jpg
   - images/207.jpg
   - images/208.jpg
   - images/209.jpg
   - images/logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
